/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_selfie_ibrahim_selfie_app_Opencv.h>
#include <jni.h>

extern "C" {

JNIEXPORT void JNICALL Java_com_selfie_ibrahim_selfie_1app_Opencv_handDetect
        (JNIEnv *, jclass, jlong addRgba){
    Mat
}

}

